import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Wallet from "@/Components/Wallet";
import TodoList from "@/Components/TodoList";
import AddTodo from "@/Components/AddTodo";
import { useEffect, useState } from "react";
import Reward from "@/Components/Reward";
import ClaimReward from "@/Components/ClaimReward";
import TotalValueLock from "@/Components/TotalValueLock.tsx";
import { getList } from "@/helper";
import { TODO_ADDRESS } from "@/contracts/Address";
import { TODO_ABI } from "@/contracts/ABIS/TodoList";
import { ethers } from "ethers";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isTx, setIsTx] = useState(false);
  const [data, setData] = useState([]);
  const [account, setAccount] = useState("");

  useEffect(() => {
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner();
    const contract = new ethers.Contract(TODO_ADDRESS, TODO_ABI, signer);

    contract.on(
      "TaskCreated",
      async (id: Number, work: string, status: boolean) => {
        alert("task created");
        setData(await getList());
      }
    );
  }, []);

  return (
    <>
      <Head>
        <title>D - ToDO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wallet account={account} setAccount={setAccount} />
      <TotalValueLock account={account} />
      <Reward account={account} />
      <div
        style={{ textAlign: "center", marginTop: "15%", marginBottom: "15%" }}
      >
        <h2 style={{ marginBottom: "30px" }}>Welcome To D-ToDo</h2>
        <AddTodo account={account} />
        <TodoList account={account} data={data} setData={setData} />
        <ClaimReward account={account} />
      </div>
    </>
  );
}
