import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Wallet from "@/Components/Wallet";
import { useState } from "react";
import TotalValueLock from "@/Components/TotalValueLock";
import Reward from "@/Components/Reward";
import AddTodo from "@/Components/AddTodo";
import TodoList from "@/Components/TodoList.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [account, setAccount] = useState("");
  const [totalValue, setTotalValue] = useState("");
  const [reward, setReward] = useState("");
  const [data, setData] = useState([]);

  return (
    <>
      <Head>
        <title>D-Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello World</h2>

      <Wallet account={account} setAccount={setAccount} />

      <TotalValueLock totalValue={totalValue} setTotalValue={setTotalValue} />
      <Reward reward={reward} setReward={setReward} />

      <AddTodo />

      <TodoList data={data} setData={setData} />
      
    </>
  );
}
